### ISSUE TITLE
Úkol č. 2 (a úkol č. 1)

### ISSUE THREAD

**Issue by ta-iva** [ta-iva/python-042023#1]
Ahoj Martine, k úkolu č. 2 z minulého týdne přibyla ještě jednička z dávné minulosti. Jestli není dočista pozdě, děkuju mockrát za kontrolu. U dvojky bylo myslím všechno jasný, u jedničky jsem občas hledala správnou cestu, ale výsledek snad sedí. V komentářích jsem nechala dvě nebo tři doplňující otázky, které mě při psaní kódu napadly. Díky moc!

**Comment by M-Kovar** [comment]
Ahoj Ivo,

skvělá práce, úkol máš krásně přehledně zpracovaný, čímž jsi mi teď po opravování méně přehledných úkolů normálně úplně udělala radost :D. Opravdu radost takový úkol opravovat - neodevzdat ho by byla škoda:). Líbí se mi, že jsi data a hypotézy ověřovala ještě dalšími způsoby nad rámec zadání, super! Pár komentářů:

- Pěkné použití metody `rename()` s jejím slovníkovým parametrem a úprava pořadí sloupců! A zajímavé vynucení legendy taky:).
- U důvěry ve stát a EU jsi chtěla použít pearsona, ale nakonec použila spearmana, což je asi jen přehlédnutí. Jak správně píšeš, vzhledem k normalitě dat se víc hodí pearson.
- U důvěry ve stát a EU se hodí do hypotéz doplnit "lineární", tedy že "(ne)existuje lineární závislost". Testujeme totiž lineární závislost (korelaci), ale v datech by mohla být i nelineární závislost, kterou bychom mohli testovat jinými způsoby. Prý se dají použít i metody pro nelineární korelaci, např. "distance correlation" - podrobnosti neznám, jen jsem si přečetl, že existuje:).
- U důvěry ve stát a EU mi přijde vyjádření k zamítnutí hypotézy opačné ("...odkazují na nemožnost zamítnout nulovou hypotézu"). Vzhledem k p<0.05 H0 zamítáme.
- U důvěry v EU a euro se mi zdá závěr taky opačný. Vzhledem k p>0.05 nezamítáme H0, tzn. "neprokázali jsme, že by se důvěra lišila".

Úkol píšu jako splněný a dobrovolně ho můžeš upravit podle komentářů. Ještě mi prosím založ nové Issue zvlášť na úkol 1, ať je v tom větší pořádek a nemíchají se komentáře. Díky a budu se těšit na další úkol(y) :-).

**Comment by ta-iva** [comment]
Ahoj Martine, 

díky moc za kontrolu i vstřícnost, mě zas hrozně potěšilo, že ti ta úprava přišla fajn - jednak jsem ráda, že jsem si mohla konečně vyzkoušet Jupyter notebook v praxi (na tvorbu výstupů je fakt skvělej), a pak že moje zvnitřnělá potřeba dbát na štábní kulturu není jen obsese, ale může být někdy i smysluplná :) 

Potvrzuju pravdivost všech tvých komentů, ke konci jsem zjevně spěchala, a to jsem si říkala, že už se nikdy nenechám vztahem p-hodnoty a hypotéz nachytat :) Opraveno a navrch jsem přihodila KDE graf, zajímalo mě, jestli potvrdí podobnost rozdělení. Pobavil mě ten můj přehmat se Spearmanem - on (jak jsem se teď též dočetla) je totiž zrovna testem i některých nelineárních závslostí, takže to bezděčné vynechání termínu "lineární" vlastně v důsledku sedlo :) Asi není náhoda, že oba testy vyšly skoro totožně, taky dobrý porovnání.

Ještě jednou díky,
Iva
