### ISSUE TITLE
Úkol č. 1

### ISSUE THREAD

**Issue by ta-iva** [ta-iva/python-042023#2]
Ahoj Martine, 

přihazuju samostatné issue k úkolu, co měl být už dávno splněn :) 

Díky!
Iva

**Comment by M-Kovar** [comment]
Ahoj Ivi,

dobrá práce, úkol máš správně a přehledně zpracovaný, píšu splněno. Líbí se mi, že ses nezalekla nejasností a chyb a zvídavě našla řešení:). Taky je výborné, že data průběžně kontroluješ přes `shape` a zobrazení tabulkou, díky čemuž snáz odhalíš případné chyby. Pár komentářů seřazených podle kódu:

- Metodu `filter()` jsem snad ani neznal, díky za rozšíření obzorů:). Na výběr sloupců jsi ji využila pěkně - jde to případně udělat jednoduše i jako `us_presidents = us_presidents_orig[["year", "state", "candidate", "candidatevotes", "totalvotes", "party_simplified"]]`.
- Konverze "agregátu" zpět na df: Není potřeba, "agregát" se využil jen pro správné provedení metody `rank()`, ale `us_presidents` je stále normální DataFram, (jen se do něj přidal sloupec rank). Ohledně `to_frame()` vs `DataFrame()` a `reset_index()` je myslím celkem jedno, co použiješ.
- Při použití `shift()` je potřeba data nejdřív grupovat, abychom působnost shiftu ohraničili a data nám "nepřetékala", kam nechceme, tzn. v prvním případě třeba z posledního roku Alabamy do prvního roku Aljašky atd. Takže v prvním případě jako `winners.groupby("state")["party_simplified"].shift(periods=1)` a ve druhém jako `top2_candidates.groupby(["year","state"])["candidatevotes"].shift(periods=-1)`.
- Úpravu dat roku 1976 na NaN se určitě hodí udělat. Použití `pandas.NA` by mělo být v pohodě. Další běžná možnost je pythonovský `float("nan")` jakožto univerzálnější (ne-pandasí) hodnota.
- Graf prvních x států: Jelikož máme data z předchozího roku seřazená, stačí vzít třeba `swing_states.iloc[:10]`.
- Podmínku pro výběr nejlepších dvou kandidátů lze napsat i jako `us_presidents[us_presidents["rank"] <= 2]`.
- Počítání `top2_candidates["abs_diff"]`: Rozdíl ve výkonu s našimi mini daty bude zanedbatelný, ale s většími netuším, muselo by se to vyzkoušet. Ale vlastně si nejsem jistý, jak přesně jsi tu druhou metodu s podmínkou jen pro `rank == 1.0` myslela:).
- Obecně k měření doby trvání provedení kódu: Lze měřit modulem time, příklad a popis: [](https://www.programiz.com/python-programming/examples/elapsed-time). Aby se rozdíl v čase projevil, hodí se obvykle příkaz spustit ve for cyklu třeba milionkrát po sobě.
- Chválím za `select()` a použití proměnné `conditions` pro vytvoření `party_change`:).
- Nesnáze s `aggfunc`: Super, že sis s tím poradila. Logiku, kdy a proč které aggfunc fungují a nefungují, nechápu, takže nemám co dál komentovat :D.
