### ISSUE TITLE
Úkol č. 4

### ISSUE THREAD

**Issue by ta-iva** [ta-iva/python-042023#3]
Ahoj Martine, jak už se na poslední chvíli stává, vše se spiklo, nejen v jupyteru celej večer řeším jednu prazvláštnost za druhou, ale ještě se prozradilo, jak málo umím s gitem, kdy došlo ke konfliktu většímu než malému a z validního souboru je invalida... posílám issue, ať učiním povinnosti zadost a jdu na tom ještě vyšívat :) Už je mi hloupý říkat to pořád dokola, ale: velké díky za trpělivost a super konstruktivní přístup, je to pro mě v těchto termných chvílích velké povzbuzení :D

**Comment by M-Kovar** [comment]
Ahoj Ivi,

i přes všechna spiknutí, nesnáze (které člověka nejvíc naučí) a temnotu jsi zase vyprodukovala moc pěkný úkol a máš splněno:-). Katastrofy v gitu jsou strašlivé, nevím, jak Ty, ale já se jich bojím extrémně :D. A díky za milá slova, čtou se krásně a neomrzí:). V úkolu máš vše správně. Pár komentářů:

- Je možné ponechat výstupní proměnnou y tak, jak je, tj. binární yes/no? Není třeba ji převádět explicitně na čísla 1/0? -> Myslím si, že převod není potřeba, algoritmy by si měly poradit s obojím. Ale vstupní textové proměnné bývá potřeba převádět, jelikož třeba KNN má problém zahrnout text do počítání vzdáleností.
- Až teď jsem se podívala do nápovědy, podezřelá je uvedená odlišná hodnota hledané metriky zejména u algoritmu LinearSVC -> U Jirky vidím precision LinearSVC 64 %, Tobě vyšlo cca 67 %, což mi přijde v pohodě. Nebo myslíš jiná čísla? Rozdíl není tak velký, navíc Jirka ve svém "oficiálním" řešení nepoužil `stratify`, což bych si klidně tipnul, že takový menší rozdíl k horšímu způsobit může. Taky je zajímavé, že Jirka zařadil `campaign` mezi kategorické parametry, asi omylem, což s výsledky taky trochu pohne - skoro bych čekal, že i víc. 
- ... Zároveň chválím použití `stratify` - jak vidno z matice záměn, v tomhle cvičení se zrovna hodí, protože máme velký nepoměr mezi daty pro "yes" a "no". Prvních je asi 26krát víc než druhých, takže se hodí přes `stratify` zajistit, aby se mezi trénovací a testovací sadu rozdělily rovnoměrně (ve stejném poměru).
- Máš pravdu, `encoded_columns.toarray()` opravdu pochází ze scipy, jelikož `encoded_columns` je objekt typu `scipy.sparse._csr.csr_matrix` a ten si v sobě nese metodu `toarray()`, [tuto](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.toarray.html). Což možná může být i příčinou nezobrazení specifikace, jelikož VS Code "na první pohled" nevidí do proměnné `encoded_columns`, takže neví, z jakého modulu metoda pochází. Nebo něco v tom smyslu:). Metodu a proměnnou můžeme narychlo prozkoumat třeba takto:
![image](https://github.com/ta-iva/python-042023/assets/7311525/85f9bf21-d911-4cee-8df1-42e973b6221c)

Tak to je vše. Díky za spolupráci, přeju hodně štěstí i v dalších datových dobrodružstvích a snad se potkáme na pivu v Brně :-).
